webservice/app/__init__.py
from flask import Flask, Blueprint
from utils import *
import os


DB_TYPE = os.getenv('DB_TYPE')
DB_URL = os.getenv('DB_URL')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USERNAME = os.getenv('DB_USERNAME')
DB_PASSWORD = os.getenv('DB_PASSWORD')
db_manager = TweetDatabaseHandler(db_path=f"{DB_TYPE}://{DB_USERNAME}:{DB_PASSWORD}@{DB_URL}:{DB_PORT}/{DB_NAME}")

HYPOTHESIS_URL = os.getenv('HYPOTHESIS_URL')
HYPOTHESIS_GROUP = os.getenv('HYPOTHESIS_GROUP')
HYPOTHESIS_TOKEN = os.getenv('HYPOTHESIS_TOKEN')
hypothesis_manager = TweetHypothesisHandler(group=HYPOTHESIS_GROUP, token=HYPOTHESIS_TOKEN, hypothesis_api_url=HYPOTHESIS_URL)


app = Flask(__name__)

URL_PREFIX = os.getenv('URL_PREFIX')
bp = Blueprint('main', __name__, template_folder='templates', static_folder='static', url_prefix=URL_PREFIX)

from app import routes

app.register_blueprint(bp, url_prefix=URL_PREFIX)

webservice/app/routes.py
from app import app, bp, db_manager, hypothesis_manager
from flask import render_template, request, redirect

@bp.route(f'/')
@bp.route(f'/list-records')
def all_records():
    data = db_manager.get_all_records()
    return render_template("all-records.html")

@bp.route(f'/list-records-data')
def all_records_data():
    data = db_manager.get_all_records()
    data = [[d['twitter_id'],d['annotation_priority'],d['annotation_count'],f"<a href='{bp.url_prefix}/record/{d['twitter_id']}'>link</a>'"] for d in data if d['annotation_priority'] > 0]
    return {'records_data': data}

@bp.route(f'/record/<record_id>')
def single_record(record_id):
    data = db_manager.get_record(record_id)
    return render_template("single-record.html", data=data)
    
@bp.route(f'/update-record')
def update_record():
    url = request.referrer
    record_id = url.split('/')[-1]
    annotations = hypothesis_manager.get_annotations(url)
    r = db_manager.update_annotations(record_id, list(annotations))
    return r
    
@bp.route(f'/random-record')
def random_record():
    next_record = db_manager.get_next_record()
    url = f"{bp.url_prefix}/record/{next_record['twitter_id']}"
    return redirect(url, code=302)

webservice/app/templates/.ipynb_checkpoints/all-records-checkpoint.html
<html>
    <head>
        <link rel='stylesheet' href='https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css'>
        <link rel='stylesheet' href='/static/css/style.css'>
        <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
        <script src='https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js'></script>
        <script src='/static/js/records-table.js'></script>
        <script>var records_data = {{ data.json_str }};</script>
    </head>
    <body>
        <div id='wrapper'>
            <div id='controls'>
                <div id='next-annotation'>
                    <a class='link' href=/random-record>Random record</a>
                </div>
            </div>
            <div id='content'>
                <table id='records-table' class='display'>
                    <thead>
                        <tr>
                            <th>Twitter ID</th>
                            <th>Annotation Priority</th>
                            <th># Annotations</th>
                            <th>Link</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Twitter ID</th>
                            <th>Annotation Priority</th>
                            <th># Annotations</th>
                            <th>Link</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </body>
</html>

webservice/app/templates/.ipynb_checkpoints/single-record-checkpoint.html
<html>
    <head>
        <link rel='stylesheet' href='/static/css/style.css'>
        <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
        <script src='/static/js/update-button.js'></script>
    </head>
    <body>
        <div id='wrapper'>
            <div id='controls'>
                <div id='next-annotation'>
                    <a class='link' href=/random-record>Random record</a>
                </div>
                <div id='to-list'>
                    <a class='link' href=/list-records>Back to records list</a>
                </div>
                <div id='update-annotations'>
                    <div class='link'>Update annotations</div>
                    <div class='response'></div>
                </div>
            </div>
            <div id='content'>
                <div class='metadata'>
                    <div><span class='key'>Twitter ID</span>: <span class='value'>{{ data.twitter_id }}</span></div>
                    <div><span class='key'>URL</span>: <span class='value'>{{ data.url }}</span></div>
                    <div><span class='key'>Date</span>: <span class='value'>{{ data.date }}</span></div>
                    <div><span class='key'>User</span>: <span class='value'>{{ data.user_name }}</span></div>
                    <div><span class='key'>Annotation priority</span>: <span class='value'>{{ data.annotation_priority }}</span></div>
                </div>
                <div class='tweet-text'>{{ data.text }}</div>
            </div>
        </div>
    </body>
</html>

webservice/app/templates/all-records.html
<html>
    <head>
        <link rel='stylesheet' href='https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css'>
        <link rel='stylesheet' href="{{ url_for('main.static', filename='css/style.css') }}">
        <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
        <script src='https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js'></script>
        <script>
            $(document).ready(function(){
                var table = $('#records-table').DataTable();
                $.get("{{ url_for('main.all_records_data') }}", function(data){
                    table.rows.add(data.records_data).draw();
                });
                
                $("#update-annotations .link").click(function(){
                    $("#update-annotations .response").html("");
                    $("#update-annotations .loading").show();
                    $.get({url: "{{ url_for('main.update_record') }}", success: function(result){
                        var response_html = "";
                        for (var k in result){
                            response_html = response_html + `<div class='row'><span class='key'>${k}</span>: <span>${result[k]}</span></div>`;
                        }
                        $("#update-annotations .loading").hide();
                        $("#update-annotations .response").html(response_html);
                    }});
                });
            });
        </script>
        <title>Clinical Trial Tweet Curation - All Records</title>
    </head>
    <body>
        <div id='wrapper'>
            <div id='controls'>
                <div id='next-annotation'>
                    <a class='link' href="{{ url_for('main.random_record') }}">Random record</a>
                </div>
            </div>
            <div id='content'>
                <table id='records-table' class='display'>
                    <thead>
                        <tr>
                            <th>Twitter ID</th>
                            <th>Annotation Priority</th>
                            <th># Annotations</th>
                            <th>Link</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Twitter ID</th>
                            <th>Annotation Priority</th>
                            <th># Annotations</th>
                            <th>Link</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </body>
</html>

webservice/app/templates/single-record.html
<html>
    <head>
        <link rel='stylesheet' href="{{ url_for('main.static', filename='css/style.css') }}">
        <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
        <script>
            $(document).ready(function(){
                $("#update-annotations .link").click(function(){
                    $("#update-annotations .response").html("");
                    $("#update-annotations .loading").show();
                    $.get({url: "{{ url_for('main.update_record') }}", success: function(result){
                        var response_html = "";
                        for (var k in result){
                            response_html = response_html + `<div class='row'><span class='key'>${k}</span>: <span>${result[k]}</span></div>`;
                        }
                        $("#update-annotations .loading").hide();
                        $("#update-annotations .response").html(response_html);
                    }});
                });
            });
        </script>
        <title>Clinical Trial Tweet Curation - {{ data.twitter_id }}</title>
    </head>
    <body>
        <div id='wrapper'>
            <div id='controls'>
                <div id='next-annotation'>
                    <a class='link' href="{{ url_for('main.random_record') }}">Random record</a>
                </div>
                <div id='to-list'>
                    <a class='link' href="{{ url_for('main.all_records') }}">Back to records list</a>
                </div>
                <div id='update-annotations'>
                    <div class='link'>Update annotations</div>
                    <div class='response'></div>
                    <div class='loading'>
                        <img src="{{ url_for('main.static', filename='img/loading.gif') }}" width='140px'>
                    </div>
                </div>
            </div>
            <div id='content'>
                <div class='metadata'>
                    <div><span class='key'>Twitter ID</span>: <span class='value'>{{ data.twitter_id }}</span></div>
                    <div><span class='key'>URL</span>: <span class='value'>{{ data.url }}</span></div>
                    <div><span class='key'>Date</span>: <span class='value'>{{ data.date }}</span></div>
                    <div><span class='key'>User</span>: <span class='value'>{{ data.user_name }}</span></div>
                    <div><span class='key'>Annotation priority</span>: <span class='value'>{{ data.annotation_priority }}</span></div>
                </div>
                <div class='tweet-text'>{{ data.text }}</div>
            </div>
        </div>
    </body>
</html>